config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #index
  get '/projects', to: 'projects#index', as: 'projects'
  
  #new
  get '/projects/new', to: 'projects#new', as: 'new_project'

  #show
  get '/projects/:id', to: 'projects#show', as: 'project'

  #create
  post '/projects', to: 'projects#create'

  #edit
  get '/projects/:id/edit', to: 'projects#edit', as: 'edit_project'

  #update
  patch '/projects/:id', to: 'projects#update'

  #destroy
  delete '/projects/:id', to: 'projects#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

    #index | READ
    def index
        @projects = Project.all
    end

    #new | READ
    def new
        @project = Project.new
    end

    #show | READ
    def show
        @project = Project.find(params[:id])
    end

    #create | CREATE
    def create
        @project = Project.create(project_params)
        redirect_to project_path(@project)
    end

    #edit | READ
    def edit
        @project = Project.find(params[:id])
    end

    #update | UPDATE
    def update
        @project = Project.find(params[:id])
        @project.update(project_params)
        redirect_to project_path(@project)
    end


    #destroy | DESTROY
    def destroy
        Project.destroy(params[:id])
        redirect_to projects_path
    end

    private

    def project_params
        params.require(:project).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kickstarter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
<div>
    <%= f.label :"project:" %>
    <%= f.text_field :name %>
    <br>
    <br>
    <%= f.label :"description:" %>
    <%= f.text_field :description %>
</div>
<br>

<%# <%= f.collection_select :class_id, Class.all, :id, :class_name %>

    <%= f.submit %>
  
<% end %>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>
<%= render 'form', project: @project %>

<br>
<%= button_to "View Project", project_path(@project), method: :get %>
<br>
<%= button_to "Back", projects_path, method: :get %>

app/views/projects/index.html.erb
<h1>Project List</h1>
<% @projects.each do |project| %>

<div>
<br>
<%=  link_to project.name, project_path(project) %>
<br>
<br>
<%= project.description %>
<br>
<br>
<%= link_to "Edit Project", edit_project_path(project) %> | <%= link_to "Delete Project", project_path(project), method: :delete, data:{confirm: "Are you sure?"}%>
<h2>__________________________________</h2>
</div>
<% end %>

app/views/projects/new.html.erb
<h1>Create New Project</h1>
<%= render 'form', project: @project %>

<br>
<%= button_to "Back", projects_path, method: :get %>

app/views/projects/show.html.erb
<h1>Project</h1>
<br>
<h1><%= @project.name %></h1>
<br>
<br>
<h2><%= @project.description %></h2>

<%= link_to "Back to home", projects_path %>